### ISSUE TITLE
Reference A.2.1 Provide test case with different kinds of Sequence Flows

### ISSUE THREAD

**Issue by apupier** [bpmn-miwg/bpmn-miwg-test-suite#187]
As mentioned in Table 12.35, we could provide sample for:
- ("normal") Sequence Flow
- Default Sequence Flow
- Conditional Sequence Flow

Use case where I detected an interchange incompatibility:
If no conditionExpression set on a Sequence Flow and the Sequence Flow is not marked as default on outgoing reference of Task/Gateways, the Sequence Flow is  a "normal" Sequence Flow. It seems that some tools are considering it as "Default Sequence Flow" (itp Commerce, Trisotech and Signavio... I'm feeling alone :s). I think that the *default* attribute on preceding Task/Gateway is missing.
Why I want to make the difference? I want to keep the condition defined by user even if it is ignored in order that if he is not sure between default and a condition he can switch easily from one to another as we kept the conditionExpression.

Based on the specification the right behavior seems to ignore the conditionExpression and be based only on the default attribute to detect Default Sequence Flow:
Table 10.3, 10.123, 10.124, 10.125 on default attribute:
> The Sequence Flow that will receive a token when none of the conditionExpressions on  other outgoing Sequence Flows evaluate to true. The default Sequence Flow should not have a conditionExpression. Any such Expression SHALL be ignored.

I
![diagramtotestdefaultsequenceflowwithcondition-1 0](https://cloud.githubusercontent.com/assets/1105127/3325776/c7c3b756-f793-11e3-84fb-cfe92abb727d.png)

>     <model:exclusiveGateway id="_jDY8EPeREeO2W5WJKwzkfQ" name="Gateway1" default="_7WRGkPeQEeO2W5WJKwzkfQ"/><model:sequenceFlow id="_7WRGkPeQEeO2W5WJKwzkfQ" name="" sourceRef="_jDY8EPeREeO2W5WJKwzkfQ" targetRef="_7TL9YPeQEeO2W5WJKwzkfQ">      <model:conditionExpression xsi:type="model:tFormalExpression" id="_kZ1xofeREeO2W5WJKwzkfQ" evaluatesToTypeRef="java:java.lang.Boolean">true</model:conditionExpression>    </model:sequenceFlow>

The litigious case is in green and I put my understanding of the right value:
![issue187bpmn-sequenceflowdefaultconditional](https://cloud.githubusercontent.com/assets/1105127/3384803/0732240a-fc61-11e3-925a-a91e1cd3905a.png)

**Comment by dgagne** [comment]
Webmeeting 7 Oct 2015
o	Benjamin will take responsibility for complete this new test case variation

**Comment by benmichel** [comment]
As discussed in the meeting, I will indeed treat this issue. However, it appears I do not have the appropriate privileges in the github to make myself owner of the issue. @falko could you pass it on to me or give me the privileges to do so myselft ?

**Comment by benmichel** [comment]
After reviewing the complete issue, I am not quite sure of what is to be done. Could someone clarify this ?
> "a new version without the dual definition of the sequence flow"

**Comment by benmichel** [comment]
Here is my proposal

https://github.com/benmichel/bpmn-miwg-test-suite/blob/master/Reference/A.2.1.bpmn
![A.2.1](https://raw.githubusercontent.com/benmichel/bpmn-miwg-test-suite/master/Reference/A.2.1.png)

**Comment by carloskavka** [comment]
The proposal seems to contradict the following statement from the specification: "If a conditional Sequence Flow is used from a source Activity, then there MUST be at least one other outgoing Sequence Flow from that Activity" (page 95, BPMN 2.0.2). In particular, "task 2" is the source of a conditional Sequence Flow, and there is no other outgoing sequence flows from that activity.

**Comment by falko** [comment]
Well spotted @carloskavka !
I think this should be fixed by adding another outgoing sequence flow.

**Comment by dgagne** [comment]
Webmeeting
o	Nothing new. Benjamin to propose alternative model

**Comment by benmichel** [comment]
Here's my proposal to resolve the missing default sequence flows issues 
[https://raw.githubusercontent.com/benmichel/bpmn-miwg-test-suite/master/Reference/A.2.1.png](url)

**Comment by dgagne** [comment]
Webmeeting 11 May 2016
o	Discussed the proposal from Benjamin, and requested that the Default flow and label out of Task 3 be removed

**Comment by SimonRinguette** [comment]
Accepted and close on June 15th meeting
