### ISSUE TITLE
Reference A.1.2: Issue with label position in XML

### ISSUE THREAD

**Issue by krat0s** [bpmn-miwg/bpmn-miwg-test-suite#193]
In the reference image A.1.2.png, the label "Data Object 2 [Reviewed]" is centered below the data object shape. In the XML, however, the coordinates for the label put it more to the right.

All other data object labels are placed and exported correctly.

**Comment by tstephen** [comment]
A.1.2 has been removed entirely from the suite as it originally stemmed from a discussion of alternative implementations that is subject of the separate sub-group.

**Comment by dgagne** [comment]
Webmeeting 7 Oct 2015
o	This particular test case variation from the alternative implementation subgroup was dropped and thus we can close this issue
