### ISSUE TITLE
Sequence Flows not imported

### ISSUE THREAD

**Issue by falko** [bpmn-miwg/bpmn-miwg-test-suite#20]
Matthias Kurz reported: "The Innovator creates both a process model as well as a diagram during update (these are two different yet linked entities in Innovator). Yet the diagram misses basic basic layout information like connectors."

Examples:
![](https://github.com/bpmn-miwg/bpmn-miwg-test-suite/raw/master/A%20-%20Fixed%20Digrams%20with%20Variations%20of%20Attributes/MID%20Innovator%2011.5.1.30223/A.1.0-import.png)
![](https://github.com/bpmn-miwg/bpmn-miwg-test-suite/raw/master/A%20-%20Fixed%20Digrams%20with%20Variations%20of%20Attributes/MID%20Innovator%2011.5.1.30223/A.2.0-import.png)

**Comment by mskurz** [comment]
Resolved. All in all, DI support has improved greatly.
