### ISSUE TITLE
Import places Events and Gateways in upper left corner

### ISSUE THREAD

**Issue by falko** [bpmn-miwg/bpmn-miwg-test-suite#21]
In MID Innovator 11 R5 E (Version 11.5.1.30223) Events and Gateways are positioned in the upper left corner of the containing Lane.

Examples:
![](https://github.com/bpmn-miwg/bpmn-miwg-test-suite/raw/master/A%20-%20Fixed%20Digrams%20with%20Variations%20of%20Attributes/MID%20Innovator%2011.5.1.30223/A.1.0-import.png)
![](https://github.com/bpmn-miwg/bpmn-miwg-test-suite/raw/master/A%20-%20Fixed%20Digrams%20with%20Variations%20of%20Attributes/MID%20Innovator%2011.5.1.30223/A.2.0-import.png)

**Comment by mskurz** [comment]
Resolved. All in all, DI support has improved greatly.
