### ISSUE TITLE
ADONIS: results of  C.1.0 missing

### ISSUE THREAD

**Issue by zmisiak** [bpmn-miwg/bpmn-miwg-test-suite#301]
Results need to be provided

**Comment by zmisiak** [comment]
Results provided

**Comment by falko** [comment]
@zmisiak I couldn't find results for C.1.0 in https://github.com/bpmn-miwg/bpmn-miwg-test-suite/tree/master/ADONIS%206.0

**Comment by falko** [comment]
Pushed them. Thx.
