### ISSUE TITLE
Reference C.1.0: No performers specified

### ISSUE THREAD

**Issue by tstephen** [bpmn-miwg/bpmn-miwg-test-suite#368]
I note that the Camunda-specific mechanism is specified in a number of places, for example: 
```
<userTask id="assignApprover" camunda:assignee="demo"
                camunda:formKey="app:assignApprover.jsf"
                name="Assign&#xA;Approver"
                implementation="webService">
...
</userTask>
```

These need to be specified in the standard way for an interchange demo of executable models.

**Comment by dgagne** [comment]
4 Feb 2015 Webmeeting
o	Discussion regarding the alternative name given to the potential owner
o	Changes approved as presented
o	Issue  closed
