### ISSUE TITLE
[Execution - 2015 demo] Conditions on Sequence Flow outgoing of Gateway with id "invoice_approved"

### ISSUE THREAD

**Issue by benmichel** [bpmn-miwg/bpmn-miwg-test-suite#412]
The Sequence Flow labeled "yes" (id="invoiceApproved"), outgoing of Gateway "Invoice approved" (id="invoice_approved"), has the following Condition Expression :

    <conditionExpression xsi:type="tFormalExpression" id="sid-0ed8a0cb-f28a-4689-bbd8-77dafd0ccfa0">${approved}</conditionExpression>

How is this expression to be resolved from a standard point of view ? What is 'approved' suppose to be since it does not seems to be a DataObject or DataStore ?
If we look at the expression language attribute of the definitions, we have

    expressionLanguage="http://www.w3.org/1999/XPath".

This means that the expression language used to resolve formal expressions should be XPATH. I thing XPATH is a good choice for the demo since it should be supported by BPMN implementors (according to chapter 10.3.3 of the spec), but if we are to use XPATH the expression should be :

    <conditionExpression xsi:type="tFormalExpression" id="sid-0ed8a0cb-f28a-4689-bbd8-77dafd0ccfa0">getDataObject('approved')</conditionExpression>

where 'approved' is a DataObject of boolean type. We could use the default type language (Table 8.1 page 53 of the spec) to define the type of this DataObject so it would be http://www.w3.org/2001/XMLSchema:boolean

ps : The same observation can be done for the Sequence Flow with id 'invoiceNotApproved'.

**Comment by dgagne** [comment]
4 Feb 2015 Webmeeting
o	It was decided that to use an alternative Expression language (to be determined between W4, Camunda and Activiti) rather than the XPATH default
