### ISSUE TITLE
[C.1.0 - demo] Conditions on sequenceflow outgoing gateway with id "invoice_approved"

### ISSUE THREAD

**Issue by benmichel** [bpmn-miwg/bpmn-miwg-test-suite#413]
The same remarks can be done as in issue #412 

if we look at Condition Expression on Sequence Flow with id="reviewSuccessful" we have :

    <conditionExpression xsi:type="tFormalExpression" id="sid-e669aead-8bad-4dbb-b282-e9f811e02f77">${clarified == 'yes'}</conditionExpression>

when we should have, if using XPATH as spécified by the definitions expressionLanguage attribute :

    <conditionExpression xsi:type="tFormalExpression" id="sid-e669aead-8bad-4dbb-b282-e9f811e02f77">getDataObject('clarified') = 'yes'</conditionExpression>

where 'clarified' would be a DataObject or DataStore with type http://www.w3.org/2001/XMLSchema:string

**Comment by dgagne** [comment]
4 feb 2015 Webmeeting
o Merged with #412 given that it relates to the selection of the expression language
