### ISSUE TITLE
[C.1.0 - demo] Alternative version of C.1.0 for the demo

### ISSUE THREAD

**Issue by benmichel** [bpmn-miwg/bpmn-miwg-test-suite#415]
I would like to submit for discussion an alternate version of the C.1.0 model

This model presents no W4 specific mecanism and only use standard BPMN mecanism such as Xsd for types definition and XPATH for formal expression and is fully executable, according to the specification.

It introduce Data Objects 'approved' and 'clarified' used to evaluate the Condition Expressions using XPATH. These Data Objects respectively reference Item Definitions ref 'xsdBool' and 'xsdString' using xsd structure reference corresponding to boolean and string. The xsd type definition are imported into the Definitions using the standard import mecanism

Finally 'Archive invoice' Service Task implementation has been set to '##unspecified' so each vendor can choose how to run the associated service

Here is an image of the definitions
![c 1 0_demo w4](https://cloud.githubusercontent.com/assets/8003851/5798551/9f0664de-9fc8-11e4-88ed-64c5d3b34709.PNG)

see https://github.com/bpmn-miwg/bpmn-miwg-demos/tree/master/2015-06-15-19-omg-technical-meeting-berlin/w4-execution-demo for the bpmn and imported files

**Comment by dgagne** [comment]
4 Feb 2015 webmeeting
o	W4 will make their additions and corrections to the original Execution Demo scenario submitted
o	It was decided to close this issue
