### ISSUE TITLE
calledElement attribute missing

### ISSUE THREAD

**Issue by mskurz** [bpmn-miwg/bpmn-miwg-test-suite#484]
**Tool**
Trisotech BPMN Modeler 5.0.10

**Output of the automated checks**
```
FINDING: checkGlobalTask                          Message: Attribute 'calledElement' does not exist; Parameter: null
```

**Trisotech Roundtrip BPMN**
```xml
<semantic:callActivity
  name="Call Activity calling a Global User Task"
  id="_a74c1d4d-db90-43ff-8920-139a300b39a5"
  startQuantity="1"
  isForCompensation="false"
  completionQuantity="1">
  <semantic:incoming>_be19c2da-316a-47f6-ad7b-eb6c82bf8609 </semantic:incoming>
  <semantic:outgoing>_ce63770e-9f4b-4bc0-a56c-88401c59f0bf </semantic:outgoing>
</semantic:callActivity>
```

**Reference BPMN**
```xml
<semantic:callActivity
  calledElement="_d4afdad7-65a5-40c6-9fee-e13ba4c0bed4"
  completionQuantity="1"
  isForCompensation="false"
  startQuantity="1"
  name="Call Activity calling a Global User Task"
  id="_a74c1d4d-db90-43ff-8920-139a300b39a5">
    <semantic:incoming>_be19c2da-316a-47f6-ad7b-eb6c82bf8609</semantic:incoming>
    <semantic:outgoing>_ce63770e-9f4b-4bc0-a56c-88401c59f0bf</semantic:outgoing>
</semantic:callActivity>
```

**Analysis**
* The *calledElement* attribute is missing in the *globalUserTask* element.

**Comment by falko** [comment]
Hi Matthias,

I'm a little confused. AFAIR the **globalUserTask** does not need an attribute **calledElement**. Only the **callActivity** does.

Cheers,
Falko

**Comment by mskurz** [comment]
Excerpt from Trisotech:

              <semantic:callActivity name="Call Activity calling a Global User Task"
                    id="_a74c1d4d-db90-43ff-8920-139a300b39a5" startQuantity="1"
                    isForCompensation="false" completionQuantity="1">
                    <semantic:incoming>_be19c2da-316a-47f6-ad7b-eb6c82bf8609
                    </semantic:incoming>
                    <semantic:outgoing>_ce63770e-9f4b-4bc0-a56c-88401c59f0bf
                    </semantic:outgoing>
             </semantic:callActivity>


Von: Falko Menge [mailto:notifications@github.com]
Gesendet: Donnerstag, 24. September 2015 11:44
An: bpmn-miwg/bpmn-miwg-test-suite
Cc: Matthias Kurz
Betreff: Re: [bpmn-miwg-test-suite] calledElement attribute missing (#484)


Hi Matthias,

I'm a little confused. AFAIR the globalUserTask does not need an attribute calledElement. Only the callActivity does.

Cheers,
Falko

**Comment by mskurz** [comment]
Hi Falko,
Yes, you are correct. I accidentally pasted the wrong excerpt. I just updated the excerpt from the Trisotech serialization. IMHO, this excerpt shows that the issue is valid.
Best Regards,
Matthias

**Comment by falko** [comment]
Yep, now that looks like an interchange issue.
