### ISSUE TITLE
Sequence flow out of task has no condition and no default

### ISSUE THREAD

**Issue by mid-back** [bpmn-miwg/bpmn-miwg-test-suite#564]
Tool name: Innovator
Tool version: 12.3.1.20212
Test case id: A.2.1
Test procedure: import
Description: The task "Task 3" has an outgoing sequence flow which is not default. The Task "Task 4" has an outgoing sequence flow without condition.

**Comment by mskurz** [comment]
This issue has been split into two issues: #586 and #587.

**Comment by lonniev** [comment]
You are pinging my Mac Notifications to death. ;-)



-- 
Lonnie VanZandt
303-900-3048

On 25 March 2016 at 13:58:09, MK (notifications@github.com) wrote:

Closed #564.

**Comment by mskurz** [comment]
Sorry. Just creating the issues identified in this week's call. But good news: Now, I'm done :-)
