### ISSUE TITLE
Empty label bounds in C.3.0

### ISSUE THREAD

**Issue by dgagne** [bpmn-miwg/bpmn-miwg-test-suite#620]
There are series of empty (blank) labels bounds in the C.3.0 models. Although the serialization is BPMN valid, these artifacts bring no interchange validation value and should be removed

**Comment by benmichel** [comment]
Correction done and commited #683

**Comment by dgagne** [comment]
Webmeeting 12 Sept 2016
Issue closed

**Comment by bzinchenko** [comment]
I repeated the test on the latest BPMN file from reference models and reproduced empty labels. Please see attached screenshot. I suggest to reopen the issue and inspect it deeper.

![c 3 0](https://cloud.githubusercontent.com/assets/5006818/20317910/be6edad0-ab70-11e6-9d28-0e18d4126883.png)
