### ISSUE TITLE
Wrongly placed files in reference folder?

### ISSUE THREAD

**Issue by matthiasgeiger** [bpmn-miwg/bpmn-miwg-test-suite#709]
Hey guys!

I just analyzed the reference models provided at https://github.com/bpmn-miwg/bpmn-miwg-test-suite/tree/master/Reference

I think the files `C.3.0-roundtrip.bpmn` and `C.2.0-roundtrip.bpmn` are accidentally added to this folder instead of ` Bonita BPM 7.2.3` with the PR #708, right?

**Comment by aSegatto** [comment]
I agree, no roundtrip files should be present in reference folder,  :smiley: 
I made a pull request to fix #711
