### ISSUE TITLE
(Minor) flaws regarding standard compliance in Reference models

### ISSUE THREAD

**Issue by matthiasgeiger** [bpmn-miwg/bpmn-miwg-test-suite#710]
Hey guys!
I loosely follow your work for some years and I think its quite impressive what you have achieved so far and I really like it that you are still committed to improve the interoperability of BPMN tools.

As mentioned in #709 I was analysing the reference models you created with a research prototype of a BPMN compliance checking tool that is rather nitpicky regarding standard compliance. This tool reported some (minor) flaws in the reference models (and partially a lot more problems in the models created by the tested tools :wink:):

- `A.2.1.bpmn`, l. 119, 145, 154, 163 and 172: These lines contain a `formalExpression` without any body. According to the specification this should not be allowed. See spec 8.3.6 p. 86, Table 8.43: cardinality of "body": 
![grafik](https://cloud.githubusercontent.com/assets/676652/21904079/b5679944-d902-11e6-98c3-fca247d7be42.png)
However, I do not really get the meaning of the highlighted text. Can you explain this to me?

- ` B.2.0.bpmn`
  - l. 363: The should be not `ioSpecification` - or at least no `dataInput` for a `subProcess`. This stated in chapter 10.3.1., p. 211: 
![grafik](https://cloud.githubusercontent.com/assets/676652/21904461/00b70c94-d904-11e6-8c82-2d87f8223cbf.png)
  - l. 361 and l. 454: Link Event correlation using names - this is at least questionable, but I've seen that this has already been discussed in #141 

- `C.1.0.bpmn` (l. 534) and also `C.3.0.bpmn` (l.73 + l.449): The processes contained here are marked as `executable`, but the `messageEventDefinition`s used there do not contain an `operationRef`. This violates the specification: 
![grafik](https://cloud.githubusercontent.com/assets/676652/21904889/8225187e-d905-11e6-91f2-3044b66db41b.png) 
(Table 10.99, p. 271)
I think in practice this attribute is not used - let alone required - by any of the BPMN engines on the market. Maybe an aspect to considered for the RTF?

What do you think of those reported problems?

Best regards
Matthias

**Comment by falko** [comment]
This issue was split up into #718, #719 & #720
