### ISSUE TITLE
formalExpression without any body

### ISSUE THREAD

**Issue by falko** [bpmn-miwg/bpmn-miwg-test-suite#718]
- `A.2.1.bpmn`, l. 119, 145, 154, 163 and 172: These lines contain a `formalExpression` without any body. According to the specification this should not be allowed. See spec 8.3.6 p. 86, Table 8.43: cardinality of "body": 
![grafik](https://cloud.githubusercontent.com/assets/676652/21904079/b5679944-d902-11e6-98c3-fca247d7be42.png)
However, I do not really get the meaning of the highlighted text. Can you explain this to me?

**Comment by falko** [comment]
This was discussed in today's web meeting and we think that this is not an issue, because the body is only needed for XMI-based model interchange but not for XMD-based interchange.

**Comment by matthiasgeiger** [comment]
Thanks for discussing my findings! 

I've a short remark/question here: I agree that a "attribute" or "subelement" named `body` is not needed for XSD-based interchange. However, in my opinion the intention of the specification here is to define that each `FormalExpression` **must** have a *body* (in the sense that there should be an actual *expression* which can be evaluated at runtime).
As shown in the table above, this is technically implemented as simple text content within the `<formalExpression>...</formalExpression>` element.
But are empty formal expressions as in `A.2.1` (e.g., `<model:conditionExpression xsi:type="model:tFormalExpression" id="_cVKUwDOCEeSknpIVFCxNIQ" language="http://www.w3.org/1999/XPath"/>` (l.119)) really allowed?
