### ISSUE TITLE
no dataInput for a subProcess

### ISSUE THREAD

**Issue by falko** [bpmn-miwg/bpmn-miwg-test-suite#719]
- ` B.2.0.bpmn`
  - l. 363: The should be not `ioSpecification` - or at least no `dataInput` for a `subProcess`. This stated in chapter 10.3.1., p. 211: 
![grafik](https://cloud.githubusercontent.com/assets/676652/21904461/00b70c94-d904-11e6-8c82-2d87f8223cbf.png)
  - l. 361 and l. 454: Link Event correlation using names - this is at least questionable, but I've seen that this has already been discussed in #141

**Comment by dgagne** [comment]
Webmeting 8 Mar 2017
The data association on the Data Store connecting it to the collapsed sub-process 2 is at fault in the B.2.0 reference. 
We will remove this data association and regenerate the reference.

**Comment by SimonRinguette** [comment]
The reference diagram was not updated at the same time as the bpmn file causing a sync issue between the depiction and the model
