### ISSUE TITLE
Naming conventions for test results with multiple diagrams per file

### ISSUE THREAD

**Issue by bzinchenko** [bpmn-miwg/bpmn-miwg-test-suite#721]
According to current testing procedure, screenshots of diagrams are named equally to the name of BPMN file, which served as an input for the test, with relevant suffixes depending on performed test. 

However, this naming schema is no more valid in case when one BPMN file contains multiple diagrams. We should decide how universal naming convention should be modified in this case.

**Comment by dgagne** [comment]
Webmeeting 14 Jun 2017
•	We will create a C.4.0 test case from the Model used for the Brussels capability demo
•	The presence of multiple diagrams for this model requires that we modify our test results submission numbering scheme to : <test id>-import.<diagramNumber>.png    e.g. C.4.0-import.1.png
•	This change will require that we modify the both the Test procedure description on the front page and do code updates to the automation tools
