### ISSUE TITLE
Inconsistent use of label bounds in the diagram

### ISSUE THREAD

**Issue by SimonRinguette** [bpmn-miwg/bpmn-miwg-test-suite#757]
Only the first diagram (Onboarding employee) has label bounds defined for shape and edges

**Comment by tstephen** [comment]
We have a heuristic for attempting to create bounds where none exist. It's not perfect, but see what you find using this version (zipped to get Github to accept)
[C.4.0.kp.bpmn.zip](https://github.com/bpmn-miwg/bpmn-miwg-test-suite/files/1525003/C.4.0.kp.bpmn.zip)
