### ISSUE TITLE
B.1.0 & B.2.0 Reference files contain 2 diagrams but files named as if only 1

### ISSUE THREAD

**Issue by tstephen** [bpmn-miwg/bpmn-miwg-test-suite#806]
Following our adoption of a new file naming convention when there are more than one diagram in a file B.1.0 and B.2.0 need to be revised. There are two options:

1. Rename `B.1.0.png` to `B.1.0.1.png` and introduce a new `B.1.0.2.png`. And a similar change for B.2.0.
2. Remove the second diagram which I seem to recall was only there because without it it was difficult / impossible to set up a callActivity to a process. Certainly, we have not focused on the called process in any of our tests.

I'd suggest option 2 is the smaller change and will prepare a pull request to discuss.

**Comment by SimonRinguette** [comment]
I'm good with the resolution. The second diagrams were never tested and were outputted by default from our tool. Thanks.
